const order = [
	{
		id: 1,
		order_number : "product name one",
		first_name:  "10",
		price:  "20",
		product_name: "product description here",	
		quantity: "2",	
		total: "100",	
		email: "ayo@test.com",	
	},
	{
		id: 2,
		order_number : "product name one",
		first_name:  "10",
		price:  "20",
		product_name: "product description here",	
		quantity: "2",	
		total: "100",	
		email: "ayo@test.com",
	},
	{
		id: 3,
		order_number : "product name one",
		first_name:  "10",
		price:  "20",
		product_name: "product description here",	
		quantity: "2",	
		total: "100",	
		email: "ayo@test.com",
	},
	{
		id: 4,
		order_number : "product name one",
		first_name:  "10",
		price:  "20",
		product_name: "product description here",	
		quantity: "2",	
		total: "100",	
		email: "ayo@test.com",
	},
	{
		id: 5,
		order_number : "product name one",
		first_name:  "10",
		price:  "20",
		product_name: "product description here",	
		quantity: "2",	
		total: "100",	
		email: "ayo@test.com",
	},
];

module.exports = order;
